-- =============================================================================
-- DevX / Astra Platform — Reference Seed Data
-- Run ONLY after 01_schema.sql has been applied to the target database.
--
-- This file is IDEMPOTENT — safe to run multiple times.
-- All INSERTs use ON DUPLICATE KEY UPDATE to avoid errors on re-runs.
--
-- Recommended order (matches FK dependencies):
--   1. subscription_types
--   2. roles
--   3. tenants           ← fill in your values
--   4. license_keys      ← generated by app tooling
--   5. subscriptions     ← fill in tenant UUID + dates
--   6. users / user_roles← created automatically on first login
-- =============================================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- =============================================================================
-- 1. SUBSCRIPTION TYPES
-- Required before any subscription row can be inserted.
-- =============================================================================

-- Aurora/prod schema uses char(36) PRIMARY KEY on id — must supply UUID() per row.
INSERT INTO `subscription_types` (`id`, `code`, `name`, `description`, `is_active`)
VALUES
  (UUID(), 'DEFAULT', 'Default Subscription', 'Initial subscription with all DevX features enabled', 1),
  (UUID(), 'STANDARD', 'Standard Subscription', 'Full access subscription with all DevX features enabled', 1),
  (UUID(), 'ENTERPRISE', 'Enterprise Subscription', 'Enterprise-grade subscription with extended token quota and user limits', 1)
ON DUPLICATE KEY UPDATE
  `name`        = VALUES(`name`),
  `description` = VALUES(`description`),
  `is_active`   = VALUES(`is_active`);

-- =============================================================================
-- 2. ROLES  (RBAC — must exist before any user_roles row)
-- =============================================================================

INSERT INTO `roles` (`id`, `name`) VALUES
  (1, 'TenantAdmin'),
  (2, 'OrgAdmin'),
  (3, 'ProjectAdmin'),
  (4, 'BusinessAnalyst'),
  (5, 'Developer'),
  (6, 'Approver'),
  (7, 'Viewer'),
  (8, 'BA')
ON DUPLICATE KEY UPDATE `name` = VALUES(`name`);

-- =============================================================================
-- 3. TENANTS
-- Replace the placeholder values below with your client's actual details.
-- Generate a fresh UUID for each environment (dev / UAT / prod).
--
-- Example (uncomment and fill in):
-- =============================================================================

-- INSERT INTO `tenants` (`id`, `name`, `status`, `created_at`)
-- VALUES (
--   'REPLACE-WITH-UUID-V4',          -- e.g. 'a1b2c3d4-0000-0000-0000-000000000001'
--   'Your Organisation Name',         -- e.g. 'Acme Corp'
--   'active',
--   NOW()
-- ) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `status` = VALUES(`status`);

-- =============================================================================
-- 4. LICENSE KEYS
-- Do NOT copy licence hashes across environments.
-- Generate via the application's internal licence-key tooling.
--
-- Template (uncomment and fill in):
-- =============================================================================

-- INSERT INTO `license_keys` (`id`, `tenant_id`, `license_hash`, `salt`, `integrity_hash`, `created_at`)
-- VALUES (
--   UUID(),
--   'REPLACE-WITH-TENANT-UUID',
--   'REPLACE_WITH_LICENSE_HASH',
--   'REPLACE_WITH_SALT',
--   'REPLACE_WITH_INTEGRITY_HASH',
--   NOW()
-- );

-- =============================================================================
-- 5. SUBSCRIPTIONS
-- Links a tenant to a subscription type.
-- max_users, token_quota, and expiry_date must be agreed with the client.
--
-- Template (uncomment and fill in):
-- =============================================================================

-- INSERT INTO `subscriptions` (
--   `id`,
--   `tenant_id`,
--   `subscription_type_id`,
--   `max_users`,
--   `token_quota`,
--   `token_used`,
--   `start_date`,
--   `expiry_date`,
--   `is_active`,
--   `created_at`
-- ) VALUES (
--   UUID(),
--   'REPLACE-WITH-TENANT-UUID',
--   (SELECT `id` FROM `subscription_types` WHERE `code` = 'DEFAULT' LIMIT 1),
--   50,               -- maximum concurrent users
--   10000000,         -- token quota (set 0 for unlimited)
--   0,
--   CURDATE(),
--   DATE_ADD(CURDATE(), INTERVAL 1 YEAR),
--   1,
--   NOW()
-- );

-- =============================================================================
-- 6. DEFAULT PERSONAS
-- Pre-loaded persona cards used in the BRD / Workflow story-generation flow.
-- These are informational personas only — not tied to RBAC.
-- =============================================================================

INSERT INTO `personas` (`id`, `name`, `role`, `color`, `focus`, `pain_points`, `goals`, `is_default`, `created_at`, `updated_at`)
VALUES
  (
    'persona-ba-001',
    'Alex Rivera',
    'Business Analyst',
    '#6366F1',
    'Requirements gathering and stakeholder alignment',
    '["Unclear requirements","Changing scope","Communication gaps between teams"]',
    '["Deliver clear BRDs","Ensure stakeholder sign-off","Reduce rework cycles"]',
    1,
    NOW(),
    NOW()
  ),
  (
    'persona-dev-001',
    'Sam Chen',
    'Senior Developer',
    '#10B981',
    'Clean architecture and scalable implementation',
    '["Ambiguous specs","Technical debt","Late-breaking requirement changes"]',
    '["Ship quality code","Maintain test coverage","Reduce production incidents"]',
    1,
    NOW(),
    NOW()
  ),
  (
    'persona-pm-001',
    'Jordan Lee',
    'Product Manager',
    '#F59E0B',
    'Product roadmap and delivery timelines',
    '["Feature creep","Resource constraints","Alignment across stakeholders"]',
    '["On-time delivery","Customer satisfaction","Predictable sprint velocity"]',
    1,
    NOW(),
    NOW()
  ),
  (
    'persona-qa-001',
    'Morgan Singh',
    'QA Engineer',
    '#EF4444',
    'Quality assurance and test automation',
    '["Missing acceptance criteria","Late defect discovery","Lack of testable requirements"]',
    '["Zero critical defects in production","Full regression coverage","Automated test suite"]',
    1,
    NOW(),
    NOW()
  ),
  (
    'persona-arch-001',
    'Casey Williams',
    'Solutions Architect',
    '#8B5CF6',
    'System design and cloud architecture',
    '["Technology sprawl","Security gaps","Integration complexity"]',
    '["Scalable cloud-native design","Security compliance","Cost-optimised infrastructure"]',
    1,
    NOW(),
    NOW()
  )
ON DUPLICATE KEY UPDATE
  `name`        = VALUES(`name`),
  `role`        = VALUES(`role`),
  `color`       = VALUES(`color`),
  `focus`       = VALUES(`focus`),
  `pain_points` = VALUES(`pain_points`),
  `goals`       = VALUES(`goals`),
  `is_default`  = VALUES(`is_default`),
  `updated_at`  = NOW();

-- =============================================================================
-- 7. GOLDEN REPOSITORIES (sample — replace/extend with real repos)
-- =============================================================================

INSERT INTO `golden_repositories` (`id`, `name`, `description`, `technologies`, `stars`, `cloud_provider`, `repository_url`, `category`, `domain`, `created_at`, `updated_at`)
VALUES
  (
    'golden-repo-001',
    'Insurance Platform Reference',
    'Reference implementation of a cloud-native insurance platform with microservices architecture',
    '["Node.js","TypeScript","React","MySQL","Redis","Docker","Kubernetes"]',
    0,
    'azure',
    NULL,
    'reference',
    'full-stack',
    NOW(),
    NOW()
  ),
  (
    'golden-repo-002',
    'DevX Core Services',
    'Core DevX platform services including authentication, RBAC, and workflow management',
    '["Express","TypeScript","Drizzle ORM","MySQL","Azure AD"]',
    0,
    'azure',
    NULL,
    'reference',
    'platform',
    NOW(),
    NOW()
  )
ON DUPLICATE KEY UPDATE
  `name`           = VALUES(`name`),
  `description`    = VALUES(`description`),
  `technologies`   = VALUES(`technologies`),
  `cloud_provider` = VALUES(`cloud_provider`),
  `category`       = VALUES(`category`),
  `domain`         = VALUES(`domain`),
  `updated_at`     = NOW();

SET FOREIGN_KEY_CHECKS = 1;

-- =============================================================================
-- VERIFICATION QUERIES (uncomment to check after running)
-- =============================================================================
-- SELECT 'subscription_types' AS `table`, COUNT(*) AS `rows` FROM `subscription_types`
-- UNION ALL
-- SELECT 'roles',    COUNT(*) FROM `roles`
-- UNION ALL
-- SELECT 'tenants',  COUNT(*) FROM `tenants`
-- UNION ALL
-- SELECT 'personas', COUNT(*) FROM `personas` WHERE `is_default` = 1
-- UNION ALL
-- SELECT 'golden_repositories', COUNT(*) FROM `golden_repositories`;

-- SELECT COUNT(*) AS total_tables
-- FROM information_schema.tables
-- WHERE table_schema = DATABASE() AND table_type = 'BASE TABLE';
-- =============================================================================
-- End of seed data
-- =============================================================================
