/**
 * Keep in sync with server/config/synthetic-preset-entities.ts (preset catalog for offline fallback).
 */

export type PresetEntity = {
  id: string;
  label: string;
  count: number;
  fields: string[];
};

export const PRESET_ENTITIES_ALL_DOMAINS: PresetEntity[] = [
  {
    id: "insurance-policy",
    label: "Insurance Policy",
    count: 13,
    fields: [
      "Policy ID",
      "Policy Number",
      "Policyholder Name",
      "Mailing Address",
      "City",
      "State",
      "Country",
      "Effective Date",
      "Expiration Date",
      "Premium Amount",
      "Deductible",
      "Coverage Type",
      "Status",
    ],
  },
  {
    id: "insurance-claim",
    label: "Insurance Claim",
    count: 12,
    fields: [
      "Claim ID",
      "Policy Number",
      "Date of Loss",
      "Loss Location Address",
      "City",
      "State",
      "Country",
      "Claim Amount",
      "Status",
      "Adjuster Name",
      "Description",
      "Settlement Date",
    ],
  },
  {
    id: "retail-order",
    label: "Retail Order",
    count: 11,
    fields: [
      "Order ID",
      "Customer ID",
      "Order Date",
      "Shipping Address",
      "City",
      "State",
      "Country",
      "Total Amount",
      "Billing Address",
      "Status",
      "Tracking Number",
    ],
  },
  {
    id: "product-inventory",
    label: "Product Inventory",
    count: 11,
    fields: [
      "Product ID",
      "SKU",
      "Product Name",
      "Category",
      "Warehouse City",
      "Warehouse State",
      "Country",
      "Quantity on Hand",
      "Unit Price",
      "Supplier ID",
      "Reorder Level",
    ],
  },
  {
    id: "patient-record",
    label: "Patient Record",
    count: 12,
    fields: [
      "Patient ID",
      "First Name",
      "Last Name",
      "Date of Birth",
      "Home Address",
      "City",
      "State",
      "Country",
      "Blood Type",
      "Emergency Phone",
      "Primary Care Physician",
      "Allergies",
    ],
  },
  {
    id: "medical-appointment",
    label: "Medical Appointment",
    count: 11,
    fields: [
      "Appointment ID",
      "Patient ID",
      "Facility Address",
      "City",
      "State",
      "Country",
      "Doctor Name",
      "Appointment Date",
      "Reason",
      "Status",
      "Duration",
    ],
  },
  {
    id: "bank-account",
    label: "Bank Account",
    count: 12,
    fields: [
      "Account ID",
      "Account Number",
      "Account Type",
      "Customer Name",
      "Branch Address",
      "City",
      "State",
      "Country",
      "Current Balance",
      "Opening Date",
      "Status",
      "Interest Rate",
    ],
  },
  {
    id: "loan-application",
    label: "Loan Application",
    count: 12,
    fields: [
      "Application ID",
      "Applicant Name",
      "Applicant Address",
      "City",
      "State",
      "Country",
      "Loan Amount",
      "Interest Rate",
      "Status",
      "Submission Date",
      "Credit Score",
      "Term Months",
    ],
  },
  {
    id: "manufacturing-work-order",
    label: "Manufacturing Work Order",
    count: 12,
    fields: [
      "Work Order ID",
      "Product SKU",
      "Plant Address",
      "City",
      "State",
      "Country",
      "Quantity",
      "Start Date",
      "Status",
      "Assigned To",
      "Completion Date",
      "Priority",
    ],
  },
  {
    id: "quality-inspection",
    label: "Quality Inspection",
    count: 12,
    fields: [
      "Inspection ID",
      "Work Order ID",
      "Site Address",
      "City",
      "State",
      "Country",
      "Inspector Name",
      "Result",
      "Notes",
      "Inspection Date",
      "Defect Count",
      "Pass Fail",
    ],
  },
  {
    id: "student-enrollment",
    label: "Student Enrollment",
    count: 12,
    fields: [
      "Student ID",
      "First Name",
      "Last Name",
      "Home Address",
      "City",
      "State",
      "Country",
      "Enrollment Date",
      "Major",
      "Status",
      "Expected Graduation",
      "GPA",
    ],
  },
  {
    id: "course-registration",
    label: "Course Registration",
    count: 11,
    fields: [
      "Registration ID",
      "Student ID",
      "Course Code",
      "Campus City",
      "Campus State",
      "Country",
      "Semester",
      "Grade",
      "Credits",
      "Instructor",
      "Status",
    ],
  },
  {
    id: "employee-record",
    label: "Employee Record",
    count: 12,
    fields: [
      "Employee ID",
      "Full Name",
      "Work Address",
      "City",
      "State",
      "Country",
      "Department",
      "Hire Date",
      "Salary",
      "Position",
      "Manager ID",
      "Status",
    ],
  },
  {
    id: "purchase-order",
    label: "Purchase Order",
    count: 12,
    fields: [
      "PO ID",
      "PO Number",
      "Vendor Name",
      "Ship To Address",
      "City",
      "State",
      "Country",
      "Order Date",
      "Total Cost",
      "Status",
      "Requested By",
      "Expected Delivery",
    ],
  },
  {
    id: "invoice",
    label: "Invoice",
    count: 13,
    fields: [
      "Invoice ID",
      "Invoice Number",
      "Customer Name",
      "Billing Address",
      "City",
      "State",
      "Country",
      "Issue Date",
      "Due Date",
      "Amount Due",
      "Status",
      "Tax Amount",
      "Payment Method",
    ],
  },
  {
    id: "support-ticket",
    label: "Support Ticket",
    count: 11,
    fields: [
      "Ticket ID",
      "Customer Name",
      "Issue Description",
      "City",
      "State",
      "Country",
      "Priority",
      "Status",
      "Assigned Agent",
      "Created Date",
      "Resolved Date",
    ],
  },
];
