import { defineConfig } from '@playwright/test';

// Auto-generated by ensurePwConfig() in server/qe/recorder-ws.ts.
// Keep in sync with the source playwright-recorder.config.ts at the repo root.
const isAws = (process.env.DEVX_HOSTING || '').toLowerCase().trim() === 'aws';
const isHeadless = isAws || process.platform === 'linux';

export default defineConfig({
  testDir: './recorded-scripts',
  use: {
    headless: isHeadless,
    // Explicit desktop viewport — must match the layout the tester recorded
    // against. Previously this was viewport:null + --start-maximized, which
    // is unreliable on Windows headed mode: Chromium would often open at
    // ~800x600, triggering responsive CSS that hides desktop-only elements
    // (e.g. Hilti's "Start saving" link), making locator.click() wait until
    // test timeout. 1920x1080 matches what window.open(width=screen.width)
    // typically captures during proxy recording on a modern monitor.
    viewport: { width: 1920, height: 1080 },
    launchOptions: {
      args: [
        // Use --window-size instead of --start-maximized so the OS window
        // matches the page viewport. --start-maximized is flaky on Windows.
        '--window-size=1920,1080',
        '--disable-blink-features=AutomationControlled',
        '--no-sandbox',
        '--disable-infobars',
      ],
    },
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',
  },
  timeout: 180000,
  retries: 0,
});
