// Config.js — Global configuration for all TestComplete test scripts
// Generated by NAT2.0 Autonomous Testing Platform
//
// Edit BASE_URL to point to your target environment.
// Import in scripts with: //USEUNIT TestData\Config

/**
 * The base URL of the application under test.
 * All page URLs are constructed as BASE_URL + '/path'.
 */
var BASE_URL = 'https://example.com';

/**
 * Short timeout — for elements that should already be visible.
 * Used in: waitForElement, clickElement, fillField
 */
var TIMEOUT_SHORT = 5000;

/**
 * Medium timeout — for page loads and navigation.
 * Used in: navigateTo, setUp, post-action waits
 */
var TIMEOUT_MEDIUM = 15000;

/**
 * Long timeout — for slow operations (file upload, report generation).
 * Use sparingly.
 */
var TIMEOUT_LONG = 30000;

/**
 * Whether to capture a screenshot on test failure.
 * Set to false to speed up suite execution during development.
 */
var SCREENSHOT_ON_FAILURE = true;

/**
 * The browser to use for testing.
 * Corresponds to TestComplete browser constants.
 * Options: 'Chrome', 'Firefox', 'Edge', 'Safari'
 */
var BROWSER = 'Chrome';
