// LoginData.js — Test data fixtures for Login page tests
// Generated by NAT2.0 Autonomous Testing Platform

/**
 * Valid test user credentials.
 * Should match an account that exists in the test environment.
 */
var VALID_USER = {
  username: 'testuser@example.com',
  password: 'Test@1234!'
};

/**
 * Invalid credentials — should be rejected by the login form.
 */
var INVALID_USER = {
  username: 'wrong@example.com',
  password: 'wrongpassword'
};

/**
 * Empty credentials — for testing form validation.
 */
var EMPTY_USER = {
  username: '',
  password: ''
};

/**
 * User with valid email format but non-existent account.
 * Useful for testing "user not found" vs "wrong password" behaviour.
 */
var NONEXISTENT_USER = {
  username: 'doesnotexist_' + new Date().getTime() + '@example.com',
  password: 'SomePassword123!'
};

/**
 * XSS payloads for security testing of form inputs.
 */
var XSS_PAYLOADS = [
  '<script>alert("xss")</script>',
  '"><img src=x onerror=alert(1)>',
  "'; DROP TABLE users; --",
  '{{7*7}}',
  '${7*7}'
];
