// LoginTests.js — Test cases for the Login page
// Generated by NAT2.0 Autonomous Testing Platform

//USEUNIT Script\Base\BaseTest
//USEUNIT Script\Pages\LoginPage
//USEUNIT TestData\Config
//USEUNIT TestData\LoginData

/**
 * Smoke test: valid credentials should redirect to the dashboard.
 */
function testValidLogin() {
  runTest('ValidLogin', BASE_URL + '/login', function() {
    login(VALID_USER.username, VALID_USER.password);
    Sys.Browser().Wait(TIMEOUT_SHORT);
    assertUrl('/dashboard');
    Log.Checkpoint('Valid login redirected to dashboard — PASS');
  });
}

/**
 * Functional test: submitting the form with no credentials should
 * show a validation error and keep the user on the login page.
 */
function testEmptyFormSubmission() {
  runTest('EmptyFormSubmission', BASE_URL + '/login', function() {
    clickLogin();
    Sys.Browser().Wait(1000);
    assertVisible(getErrorMessage(), 'Validation error shown for empty form submission');
    assertUrl('/login');
  });
}

/**
 * Functional test: wrong credentials should show an error message
 * and keep the user on the login page.
 */
function testInvalidCredentials() {
  runTest('InvalidCredentials', BASE_URL + '/login', function() {
    login(INVALID_USER.username, INVALID_USER.password);
    Sys.Browser().Wait(1500);
    assertVisible(getErrorMessage(), 'Error message shown for invalid credentials');
    assertUrl('/login');
    var errorText = getErrorText();
    Log.Message('Error message received: ' + errorText);
    Log.Checkpoint('Invalid credentials handled correctly — PASS');
  });
}

/**
 * Edge case: very long username should be handled gracefully.
 */
function testLongUsernameInput() {
  runTest('LongUsernameInput', BASE_URL + '/login', function() {
    var longUsername = '';
    for (var i = 0; i < 255; i++) { longUsername += 'a'; }
    longUsername += '@example.com';

    enterUsername(longUsername);
    enterPassword(VALID_USER.password);
    clickLogin();
    Sys.Browser().Wait(2000);

    // Test passes if the page doesn't crash (no 500 error)
    var currentUrl = Sys.Browser().URL;
    Log.Message('URL after long input: ' + currentUrl);
    Log.Checkpoint('Long username input handled without crash — PASS');
  });
}
