// SuiteRunner.js — Orchestrates all TestComplete test scripts
// Generated by NAT2.0 Autonomous Testing Platform
//
// Usage:
//   RunAllTests()  — runs the complete regression suite
//   RunSmoke()     — runs critical-path smoke tests only
//   RunRegression() — runs all tests including edge cases

//USEUNIT Script\Tests\LoginTests
//USEUNIT TestData\Config

var _passCount = 0;
var _failCount = 0;

/**
 * Runs a test function and tracks pass/fail count.
 * @param {Function} testFn - The test function to invoke
 * @param {string}   name   - The test name for logging
 */
function _runTracked(testFn, name) {
  try {
    testFn();
    _passCount++;
  } catch (e) {
    _failCount++;
    Log.Error('Suite: test failed — ' + name + ': ' + e.message);
  }
}

/**
 * Runs the complete regression suite.
 * Includes all smoke and functional tests.
 */
function RunAllTests() {
  _passCount = 0;
  _failCount = 0;
  var startTime = new Date();
  Log.Message('====================================');
  Log.Message('NAT2.0 TestComplete Suite — RunAllTests');
  Log.Message('Start: ' + startTime.toISOString());
  Log.Message('Base URL: ' + BASE_URL);
  Log.Message('====================================');

  // Login tests
  _runTracked(testValidLogin,         'testValidLogin');
  _runTracked(testEmptyFormSubmission, 'testEmptyFormSubmission');
  _runTracked(testInvalidCredentials,  'testInvalidCredentials');
  _runTracked(testLongUsernameInput,   'testLongUsernameInput');

  _logSummary(startTime);
}

/**
 * Runs only critical-path smoke tests (fastest subset).
 */
function RunSmoke() {
  _passCount = 0;
  _failCount = 0;
  var startTime = new Date();
  Log.Message('====================================');
  Log.Message('NAT2.0 TestComplete Suite — RunSmoke');
  Log.Message('Start: ' + startTime.toISOString());
  Log.Message('====================================');

  _runTracked(testValidLogin,         'testValidLogin');
  _runTracked(testEmptyFormSubmission, 'testEmptyFormSubmission');

  _logSummary(startTime);
}

/**
 * Runs the full regression suite including edge cases.
 */
function RunRegression() {
  RunAllTests(); // currently equivalent — extend as more test files are added
}

/** @private */
function _logSummary(startTime) {
  var elapsed = Math.round((new Date().getTime() - startTime.getTime()) / 1000);
  Log.Message('====================================');
  Log.Message('Suite Complete');
  Log.Message('Duration: ' + elapsed + 's');
  Log.Message('Passed:   ' + _passCount);
  Log.Message('Failed:   ' + _failCount);
  Log.Message('Total:    ' + (_passCount + _failCount));
  if (_failCount > 0) {
    Log.Error(_failCount + ' test(s) FAILED');
  } else {
    Log.Checkpoint('All ' + _passCount + ' tests PASSED');
  }
  Log.Message('====================================');
}
