name: Azure Static Web Apps CI/CD - QA

pr:
  branches:
    include:
      - main
  paths:
    include:
      - client/**
      - shared/**
      - package.json
      - package-lock.json
      - vite.config.ts
      - tailwind.config.ts
      - postcss.config.js
      - components.json
      - tsconfig.json
      - staticwebapp.config.json
      - .npmrc
    exclude:
      - server/**
      - scripts/**
      - README.md
      - docs/*
      - '*.md'
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - client/**
      - shared/**
      - package.json
      - package-lock.json
      - vite.config.ts
      - tailwind.config.ts
      - postcss.config.js
      - components.json
      - tsconfig.json
      - staticwebapp.config.json
      - .npmrc
    exclude:
      - server/**
      - scripts/**
      - README.md
      - docs/*
      - '*.md'

jobs:
- job: build_and_deploy_job
  displayName: Build and Deploy Job
  condition: or(eq(variables['Build.Reason'], 'Manual'),or(eq(variables['Build.Reason'], 'PullRequest'),eq(variables['Build.Reason'], 'IndividualCI')))
  pool:
    vmImage: ubuntu-latest
  variables:
  - group: Azure-Static-Web-Apps-gentle-hill-099ce5400-variable-group
  steps:
  - checkout: self
    submodules: true
  - task: AzureStaticWebApp@0
    inputs:
      azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN_GENTLE_HILL_099CE5400)
###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
# For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
      app_location: "/" # App source code path
      api_location: "" # Api source code path - optional
      output_location: "dist/public" # Built app content directory - optional
###### End of Repository/Build Configurations ######

