/**
 * Global teardown — runs once after all tests complete.
 * Logs a summary message. Reports are generated by the HTML reporter.
 */
async function globalTeardown(): Promise<void> {
  console.log('\n[global-teardown] All tests complete.');
  console.log('[global-teardown] HTML report: playwright-report/index.html');
  console.log('[global-teardown] Allure results: allure-results/');
  console.log('[global-teardown] Screenshots: test-results/screenshots/');
}

export default globalTeardown;
