apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "devx.labels" . | nindent 4 }}
  {{- if and .Values.service.annotations (not .Values.ingress.enabled) }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ if .Values.ingress.enabled }}ClusterIP{{ else }}{{ .Values.service.type }}{{ end }}
  selector:
    {{- include "devx.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
