// LoginPage.js — Page Object for the Login page
// Generated by NAT2.0 Autonomous Testing Platform
//
// Requires NameMapping aliases:
//   Aliases.browser.pageLogin.usernameField
//   Aliases.browser.pageLogin.passwordField
//   Aliases.browser.pageLogin.loginButton
//   Aliases.browser.pageLogin.errorMessage
//
// See NameMapping/Login.md for setup instructions.

//USEUNIT Script\Base\BaseHelper

/**
 * Returns the mapped Login page alias object.
 * All element getters use this as the root.
 *
 * @returns {Object} TestComplete Aliases.browser.pageLogin
 */
function getPage() {
  return Aliases.browser.pageLogin;
}

/**
 * Returns the username input element.
 * @returns {Object} TestComplete element
 */
function getUsernameField() {
  return getPage().usernameField;
}

/**
 * Returns the password input element.
 * @returns {Object} TestComplete element
 */
function getPasswordField() {
  return getPage().passwordField;
}

/**
 * Returns the login submit button.
 * @returns {Object} TestComplete element
 */
function getLoginButton() {
  return getPage().loginButton;
}

/**
 * Returns the error message element (visible when login fails).
 * @returns {Object} TestComplete element
 */
function getErrorMessage() {
  return getPage().errorMessage;
}

// ── Actions ────────────────────────────────────────────────────────────────────

/**
 * Enters a value into the username field.
 * @param {string} value - The username to enter
 */
function enterUsername(value) {
  fillField(getUsernameField(), value);
}

/**
 * Enters a value into the password field.
 * @param {string} value - The password to enter
 */
function enterPassword(value) {
  fillField(getPasswordField(), value);
}

/**
 * Clicks the login submit button.
 */
function clickLogin() {
  clickElement(getLoginButton());
}

/**
 * Convenience: enters username and password, then clicks login.
 * @param {string} username - The username credential
 * @param {string} password - The password credential
 */
function login(username, password) {
  enterUsername(username);
  enterPassword(password);
  clickLogin();
}

/**
 * Returns true if the error message element exists on the page.
 * @returns {boolean}
 */
function isErrorVisible() {
  return getPage().errorMessage.Exists;
}

/**
 * Returns the text content of the error message element.
 * @returns {string} error message text
 */
function getErrorText() {
  return getErrorMessage().contentText || '';
}
