/**
 * Stack Modernization - Enhanced Planning Agent
 * Combines CompatibilityCheck + RiskReport into one comprehensive planning phase
 * 
 * Outputs:
 * - plan.md: LLM-generated detailed upgrade plan based on actual code + data
 * - Updates state with compatibility and risk data
 */

import type { 
  StackModernizationState, 
  VersionSelection,
  CompatibilityCheckResult,
  RiskReportResult,
  PlanningVisualizationData,
  PerStackScore,
  RiskMatrixEntry,
} from "../types";
import { getLLMClient } from "../services/llm-selector";
import { safeMaxTokens } from "../services/token-manager";
import { trackedLLMCall } from "../services/llm-call-tracker";
import { AGENT_TOKEN_BUDGETS, buildBudgetConstraint } from "../services/token-budgets";
import { executeCompatibilityCheckAgent } from "./compatibility-check-agent";
import { executeRiskReportAgent } from "./risk-report-agent";
import { 
  PLANNING_SYSTEM_PROMPT, 
  buildPlanningMarkdownPrompt,
} from "../prompts/planning-prompts";
import { formatDocsForPlanning } from "../services/migration-doc-formatter";

/**
 * Execute comprehensive planning phase
 */
export async function executePlanningAgent(
  state: StackModernizationState
): Promise<StackModernizationState> {
  
  
  if (!state.userSelections || state.userSelections.length === 0) {
    throw new Error("Planning Agent requires userSelections to be set");
  }
  
  try {
    // Step 1: Run compatibility check
    let updatedState = await executeCompatibilityCheckAgent(state);
    
    // Step 2: Run risk assessment
    const riskReport = await executeRiskReportAgent(updatedState, state.userSelections || []);
    updatedState = {
      ...updatedState,
      riskReport
    };
    
    // Step 3: Build structured visualization data for frontend charts
    const planningVisualizationData = buildPlanningVisualizationData(updatedState);

    // Step 4: Generate comprehensive plan.md via LLM
    const planMarkdown = await generateDetailedPlanMarkdown(updatedState);
    
    const finalState: StackModernizationState = {
      ...updatedState,
      planMarkdown,
      planningVisualizationData,
      currentStage: "planning_complete",
      status: "in_progress",
    };
    
    return finalState;
    
  } catch (error) {
    console.error("[Planning] Error:", error);
    throw error;
  }
}

/**
 * Generate detailed plan.md using LLM with all analysis data + code files.
 * Falls back to a factual-only template if LLM fails.
 */
async function generateDetailedPlanMarkdown(state: StackModernizationState): Promise<string> {
  try {
    const { client, model } = getLLMClient(state.llmProvider);
    const prompt = buildPlanningMarkdownPrompt(state, model);

    // Build version enforcement reminder from user selections
    const selections = state.userSelections || [];
    const versionReminder = selections.length > 0
      ? `\n\nVersion guidance: The user selected these target versions. Use them in the plan:\n${selections.map(s => `  - ${s.package}: ${s.currentVersion} -> ${s.selectedVersion}`).join("\n")}\nDo not substitute different versions.`
      : "";

    // Inject official migration docs — budget-aware, priority-ordered per package
    const migrationDocs = state.migrationDocs ?? {};
    const docsContext = Object.keys(migrationDocs).length > 0
      ? `\n\n${formatDocsForPlanning(migrationDocs)}`
      : "";

    const budgetBlock = buildBudgetConstraint("planning", "markdown");
    const response = await trackedLLMCall(client, {
      model,
      messages: [
        { role: "system", content: `${budgetBlock}\n\n${PLANNING_SYSTEM_PROMPT}\n\nYou generate comprehensive MARKDOWN upgrade plan documents. Be thorough, specific, and reference the actual data and code files provided. Never use generic boilerplate.${versionReminder}${docsContext}` },
        { role: "user", content: prompt },
      ],
      temperature: 0,
      max_tokens: safeMaxTokens(AGENT_TOKEN_BUDGETS.planning, model),
    }, { analysisId: state.analysisId, phase: "planning", agent: "Planning" });

    let llmMarkdown = response.choices[0]?.message?.content?.trim() || "";
    if (llmMarkdown.length > 300) {
      // Post-process: fix any version mismatches the LLM introduced
      llmMarkdown = enforceVersionsInMarkdown(llmMarkdown, selections);
      return `# Stack Upgrade Plan\n\n*Generated on: ${new Date().toISOString()}*\n\n${llmMarkdown}\n\n---\n*Generated by DevX Stack Modernization Planning Agent v2.0*`;
    }
    throw new Error("LLM returned insufficient content");
  } catch (error) {
    console.warn("[Planning] LLM markdown generation failed, using factual fallback:", error instanceof Error ? error.message : error);
    return generatePlanMarkdownFallback(state);
  }
}

function generatePlanMarkdownFallback(state: StackModernizationState): string {
  const compat = state.compatibilityCheck;
  const risk = state.riskReport;
  const selections = state.userSelections || [];
  const repoProfile = state.repoProfile;
  const depGraph = state.dependencyGraph;

  return `# Stack Upgrade Plan

*Generated on: ${new Date().toISOString()}*

## Selected Upgrades
${selections.map(s => `- **${s.package}**: ${s.currentVersion} -> ${s.selectedVersion} (${s.category})`).join("\n")}

## Compatibility
- Compatible: ${compat?.compatible ? "Yes" : "Issues Detected"}
- Confidence: ${compat?.confidence || 0}%
- Warnings: ${compat?.warnings?.length || 0}
- Conflicts: ${compat?.conflicts?.length || 0}
${compat?.warnings?.length ? "\n### Warnings\n" + compat.warnings.slice(0, 10).map((w: any) => `- [${w.severity}] ${w.message}`).join("\n") : ""}

## Risk Assessment
- Overall Risk: ${risk?.overallRisk || "Unknown"}
- Confidence Score: ${risk?.confidenceScore || 0}/100
- Breaking Changes: ${risk?.breakingChanges?.length || 0}
${risk?.breakingChanges?.length ? "\n### Breaking Changes\n" + risk.breakingChanges.slice(0, 10).map((bc: any) => `- ${bc.package || bc.title || "?"}: ${bc.description || ""}`).join("\n") : ""}

## Project Info
- Type: ${repoProfile?.projectType || "Unknown"}
- Files: ${repoProfile?.fileStructure?.totalFiles || 0}
- Dependencies: ${(depGraph?.directDependencies?.length || 0) + (depGraph?.transitiveDependencies?.length || 0)}

---
*Generated by DevX Stack Modernization Planning Agent v2.0 (fallback mode)*
`;
}

// ─── Visualization data builder (unchanged - uses structured state data) ───

function buildPlanningVisualizationData(state: StackModernizationState): PlanningVisualizationData {
  const selections = state.userSelections || [];
  const compat = state.compatibilityCheck;
  const risk = state.riskReport;
  const versionInt = state.versionIntelligence || [];

  const effortMap: Record<string, number> = { trivial: 1, low: 2, medium: 3, high: 4, "very-high": 5 };

  const perStackScores: PerStackScore[] = selections.map((sel) => {
    const changeType = determineChangeType(sel.currentVersion, sel.selectedVersion);
    const riskLevel = changeType === "Major" ? 80 : changeType === "Minor" ? 40 : 15;
    const breakingCount = risk?.breakingChanges?.filter(
      (bc: any) => (bc.package || "").toLowerCase() === sel.package.toLowerCase()
    ).length || 0;
    const effort = changeType === "Major" ? "high" : changeType === "Minor" ? "medium" : "low";

    let compatScore = 85;
    if (changeType === "Major") compatScore -= 30;
    if (breakingCount > 0) compatScore -= breakingCount * 10;
    compatScore = Math.max(10, Math.min(100, compatScore));

    return {
      name: sel.package,
      category: (sel.category as any) || categorizeForChart(sel.package),
      currentVersion: sel.currentVersion,
      targetVersion: sel.selectedVersion,
      compatibilityScore: compatScore,
      riskScore: riskLevel + breakingCount * 5,
      breakingChangesCount: breakingCount,
      effort: effort as any,
      effortNumeric: effortMap[effort] || 3,
    };
  });

  const riskMatrix: RiskMatrixEntry[] = (risk?.failureScenarios || []).map((fs: any) => {
    const likelihoodMap: Record<string, number> = { low: 1, medium: 3, high: 5 };
    return {
      scenario: fs.scenario || "Unknown",
      likelihood: likelihoodMap[(fs.likelihood || "medium").toLowerCase()] || 3,
      impact: likelihoodMap[(fs.impact || "medium").toLowerCase()] || 3,
      category: fs.category || "general",
    };
  });

  if (riskMatrix.length === 0 && (risk?.breakingChanges?.length || 0) > 0) {
    for (const bc of (risk?.breakingChanges || []).slice(0, 5)) {
      riskMatrix.push({
        scenario: `Breaking change in ${(bc as any).package || "unknown"}`,
        likelihood: 3,
        impact: (bc as any).severity === "high" ? 4 : 2,
        category: "breaking-change",
      });
    }
  }

  const secScore = state.securityAssessment?.score || 70;
  const compatConfidence = compat?.confidence || 70;
  const avgEffort = perStackScores.length > 0
    ? Math.round(perStackScores.reduce((s, p) => s + p.effortNumeric, 0) / perStackScores.length * 20)
    : 50;
  const avgRisk = perStackScores.length > 0
    ? Math.round(perStackScores.reduce((s, p) => s + p.riskScore, 0) / perStackScores.length)
    : 30;
  const testCov = state.codeQuality?.patterns?.testCoverage;
  const testScore = testCov === "high" ? 85 : testCov === "moderate" ? 60 : testCov === "low" ? 30 : 15;

  // Effort distribution
  const effortBuckets: Record<string, number> = {};
  for (const s of perStackScores) {
    effortBuckets[s.effort] = (effortBuckets[s.effort] || 0) + 1;
  }
  const effortDistribution = ["trivial", "low", "medium", "high", "very-high"]
    .filter(e => effortBuckets[e])
    .map(e => ({ label: e, count: effortBuckets[e] }));

  // Breaking change severity distribution
  const sevBuckets: Record<string, number> = { low: 0, medium: 0, high: 0 };
  for (const bc of (risk?.breakingChanges || [])) {
    const sev = (bc as any).severity || "medium";
    sevBuckets[sev] = (sevBuckets[sev] || 0) + 1;
  }
  const severityDistribution = [
    { label: "Low", count: sevBuckets["low"], color: "#22c55e" },
    { label: "Medium", count: sevBuckets["medium"], color: "#eab308" },
    { label: "High", count: sevBuckets["high"], color: "#ef4444" },
  ].filter(s => s.count > 0);

  // Required changes by type
  const changeBuckets: Record<string, number> = {};
  for (const rc of (risk?.requiredChanges || [])) {
    const t = (rc as any).type || "code";
    changeBuckets[t] = (changeBuckets[t] || 0) + 1;
  }
  const requiredChanges = Object.entries(changeBuckets).map(([type, count]) => ({ type, count }));

  const totalBreakingChanges = (risk?.breakingChanges || []).length;

  return {
    perStackScores,
    riskMatrix,
    overallHealth: {
      security: secScore,
      compatibility: compatConfidence,
      effort: 100 - avgEffort,
      risk: 100 - avgRisk,
      testCoverage: testScore,
    },
    effortDistribution,
    severityDistribution,
    upgradeOrder: risk?.upgradeOrder || [],
    recommendation: risk?.recommendation || compat?.recommendation || "unknown",
    totalBreakingChanges,
    requiredChanges,
    keyInsights: risk?.keyInsights || [],
  };
}

function categorizeForChart(packageName: string): "runtime" | "framework" | "database" | "library" | "build-tool" {
  const n = packageName.toLowerCase();
  if (["node", "python", "java", ".net", "dotnet", "go", "ruby"].some((r) => n.includes(r))) return "runtime";
  if (["react", "angular", "vue", "express", "django", "flask", "spring"].some((f) => n.includes(f))) return "framework";
  if (["pg", "mysql", "mongo", "redis", "sqlite", "sql"].some((d) => n.includes(d))) return "database";
  if (["webpack", "vite", "rollup", "babel", "typescript"].some((b) => n.includes(b))) return "build-tool";
  return "library";
}

function determineChangeType(current: string, target: string): string {
  const currParts = current.split(".");
  const targParts = target.split(".");
  if (currParts[0] !== targParts[0]) return "Major";
  if (currParts[1] !== targParts[1]) return "Minor";
  return "Patch";
}

/**
 * Post-process LLM-generated plan markdown to fix version mismatches.
 * The LLM sometimes substitutes its own "recommended" versions instead of
 * the user's selected versions (e.g., ".NET 8" instead of ".NET 10").
 * This function deterministically corrects those in the markdown text.
 */
function enforceVersionsInMarkdown(markdown: string, selections: VersionSelection[]): string {
  let result = markdown;

  // Contextual keywords that indicate a version target (not historical references)
  const targetContexts = [
    "upgrade\\s+to",
    "migrate\\s+to",
    "target\\s+version",
    "→",
    "->",
    "=>",
    "to\\s+version",
    "update\\s+to",
    "bump\\s+to",
  ];
  const targetContextPattern = `(?:${targetContexts.join("|")})\\s*`;

  for (const sel of selections) {
    const pkg = (sel.package || "").toLowerCase();
    const targetVer = (sel.selectedVersion || "").replace(/^v/i, "").trim();
    const currentVer = (sel.currentVersion || "").replace(/^v/i, "").trim();
    if (!targetVer || !currentVer) continue;

    const targetMajor = parseInt(targetVer.split(".")[0], 10);
    const currentMajor = parseInt(currentVer.split(".")[0], 10);
    if (isNaN(targetMajor) || isNaN(currentMajor)) continue;

    if (pkg.includes(".net") || pkg.includes("dotnet") || pkg === "dotnet") {
      for (let wrongMajor = currentMajor + 1; wrongMajor < targetMajor; wrongMajor++) {
        // Only replace in "upgrade to" / "migrate to" / arrow contexts
        result = result.replace(
          new RegExp(`(${targetContextPattern})\\.NET\\s+${wrongMajor}(\\.0)?\\b`, "gi"),
          `$1.NET ${targetMajor}`
        );
        // TFM monikers (netX.0) in code-like contexts are always targets
        result = result.replace(
          new RegExp(`(<TargetFramework>)net${wrongMajor}\\.0(<\\/TargetFramework>)`, "g"),
          `$1net${targetMajor}.0$2`
        );
      }
    }
  }

  return result;
}

