// BaseTest.js — Test lifecycle management for all TestComplete test scripts
// Generated by NAT2.0 Autonomous Testing Platform
//
// Usage: Add //USEUNIT Script\Base\BaseTest at the top of test script files.

//USEUNIT Script\Base\BaseHelper
//USEUNIT TestData\Config

/**
 * Sets up the test environment before a test runs.
 * Navigates to the target URL, maximises the browser window,
 * and clears browser cookies.
 *
 * @param {string} url - The URL to open at the start of the test
 */
function setUp(url) {
  Log.Message('--- Test Setup ---');
  navigateTo(url);
  Sys.Browser().BrowserWindow(0).Maximize();
  Sys.Browser().ClearCookies();
  Log.Message('Setup complete: browser maximised, cookies cleared');
}

/**
 * Tears down the test environment after a test runs.
 * Captures a failure screenshot if the test did not pass.
 *
 * @param {string}  testName - The name of the test (used in screenshot label)
 * @param {boolean} passed   - Whether the test passed
 */
function tearDown(testName, passed) {
  if (!passed) {
    takeScreenshot(testName + '_FAIL');
    Log.Error('Test FAILED: ' + testName);
  } else {
    Log.Message('Test PASSED: ' + testName);
  }
  var timestamp = new Date().toISOString();
  Log.Message('Test complete at ' + timestamp + ': ' + testName);
}

/**
 * Runs a test function with automatic setup and teardown.
 * Catches any exception thrown by the test function, logs it,
 * and records pass/fail state.
 *
 * @param {string}   testName - Descriptive name of the test
 * @param {string}   url      - The URL to navigate to during setup
 * @param {Function} testFn   - The test body function to execute
 *
 * @example
 * function testValidLogin() {
 *   runTest('ValidLogin', BASE_URL + '/login', function() {
 *     login('user@example.com', 'password123');
 *     assertUrl('/dashboard');
 *   });
 * }
 */
function runTest(testName, url, testFn) {
  var passed = false;
  Log.AppendFolder('Test: ' + testName);

  try {
    setUp(url);
    testFn();
    passed = true;
  } catch (e) {
    Log.Error('Exception in ' + testName + ': ' + e.message);
  } finally {
    tearDown(testName, passed);
    Log.PopLogFolder();
  }
}
