// BaseHelper.js — Core interaction utilities for all TestComplete test scripts
// Generated by NAT2.0 Autonomous Testing Platform
//
// Usage: Add //USEUNIT Script\Base\BaseHelper at the top of any script
// that needs these functions.

//USEUNIT TestData\Config

/**
 * Navigates the browser to the given URL and waits for the page to load.
 *
 * @param {string} url - The full URL to navigate to
 */
function navigateTo(url) {
  Log.Message('Navigating to: ' + url);
  Browsers.Item(btChrome).Run(url);
  Sys.Browser().Wait(TIMEOUT_MEDIUM);
  Log.Message('Navigation complete: ' + Sys.Browser().URL);
}

/**
 * Fills an input field. Selects all existing text before typing
 * to replace it cleanly.
 *
 * @param {Object} element - TestComplete element object (from NameMapping)
 * @param {string} value   - The value to type into the field
 */
function fillField(element, value) {
  waitForElement(element, TIMEOUT_SHORT);
  element.Click();
  element.Keys('[SelectAll]');
  element.Keys(value);
  Log.Message('Filled field with value length: ' + value.length);
}

/**
 * Clicks an element after waiting for it to be enabled.
 *
 * @param {Object} element - TestComplete element object (from NameMapping)
 */
function clickElement(element) {
  waitForElement(element, TIMEOUT_SHORT);
  element.WaitProperty('Enabled', true, TIMEOUT_SHORT);
  element.Click();
  Log.Message('Clicked: ' + element.Name);
}

/**
 * Asserts an element is visible. Logs a checkpoint on pass, throws on fail.
 *
 * @param {Object} element - TestComplete element object
 * @param {string} message - A descriptive label for the checkpoint
 * @throws {Error} if the element does not exist
 */
function assertVisible(element, message) {
  if (!element.Exists) {
    Log.Error(message + ': FAIL — element not found');
    throw new Error('assertVisible failed: ' + message);
  }
  Log.Checkpoint(message + ': PASS');
}

/**
 * Asserts an element's text matches the expected value.
 * Checks contentText first, falls back to Caption.
 *
 * @param {Object} element  - TestComplete element object
 * @param {string} expected - The expected text value
 */
function assertText(element, expected) {
  var actual = '';
  try {
    actual = element.contentText || element.Caption || '';
  } catch (e) {
    Log.Error('assertText: could not read element text — ' + e.message);
    throw e;
  }
  actual = actual.trim();
  if (actual !== expected) {
    Log.Error(
      'assertText FAIL — expected: "' + expected + '", actual: "' + actual + '"'
    );
    throw new Error('Text mismatch: expected "' + expected + '" got "' + actual + '"');
  }
  Log.Checkpoint('assertText PASS: "' + expected + '"');
}

/**
 * Asserts the current browser URL contains the expected fragment.
 *
 * @param {string} expected - The URL substring to assert
 */
function assertUrl(expected) {
  var actual = Sys.Browser().URL;
  if (actual.indexOf(expected) === -1) {
    Log.Error('assertUrl FAIL — expected URL to contain "' + expected + '", actual: "' + actual + '"');
    throw new Error('URL mismatch: expected "' + expected + '" in "' + actual + '"');
  }
  Log.Checkpoint('assertUrl PASS: URL contains "' + expected + '"');
}

/**
 * Polls for element.Exists up to timeoutMs milliseconds.
 * Throws if the element is not found within the timeout.
 *
 * @param {Object} element   - TestComplete element object
 * @param {number} timeoutMs - Maximum wait time in milliseconds
 * @throws {Error} if the element is not found within the timeout
 */
function waitForElement(element, timeoutMs) {
  var start   = GetCurrentTime().getTime();
  var elapsed = 0;
  var found   = false;

  while (elapsed < timeoutMs) {
    if (element.Exists) {
      found = true;
      break;
    }
    Delay(200);
    elapsed = GetCurrentTime().getTime() - start;
  }

  if (!found) {
    var msg = 'waitForElement: element not found after ' + timeoutMs + 'ms';
    Log.Error(msg);
    throw new Error(msg);
  }
}

/**
 * Takes a screenshot and saves it to the TestComplete log with a timestamp.
 *
 * @param {string} name - A descriptive label for the screenshot
 */
function takeScreenshot(name) {
  var timestamp = new Date().toISOString().replace(/[:.]/g, '-');
  var label     = name + '_' + timestamp;
  Log.Picture(Sys.Desktop.Picture(), label);
  Log.Message('Screenshot captured: ' + label);
}

/**
 * Selects all text in a field and types a new value.
 * Equivalent to Ctrl+A then type.
 *
 * @param {Object} element - TestComplete element object
 * @param {string} value   - The value to type
 */
function clearAndType(element, value) {
  waitForElement(element, TIMEOUT_SHORT);
  element.Click();
  element.Click();
  element.Click(); // triple-click selects all in most inputs
  element.Keys(value);
  Log.Message('clearAndType: entered ' + value.length + ' characters');
}
